Add logos das empresas patrocinadoras
pythonbrasil/pybr2022-site pull request #83
Opened 2022-08-11 00:53 UTC by rougeth

2022-08-12 01:57 UTC, wasp-lahis commented
Assim que me responderem atualizo por aqui o/

2022-08-12 21:09 UTC, wasp-lahis requested changes
## Ajustes solicitados:

cc @rougeth @richardson-souza 

**[INDT] R:** 

> Estamos com um problema na atualização do certificado https em nosso site, porém nossa TI já está em tratativa. Por isso o link está quebrado.
> 
> Pode inserir o link pra nossa página do site mesmo,  https://www.indt.org.br/,  pois já estamos resolvendo o problema e logo voltará ao ar.
> 
> Aplicação do logo está ok.

**[LUIZALABS]R:** 

> Sobre o site logo está correto, só achamos muito perto um logo do outro, seria possível ajustar esse ponto?

**[VINTA]R:** 

> Tudo ok, pode seguir. Obrigada!

2022-08-12 21:32 UTC, rougeth commented
@wasp-lahis atualizei o link e o espaço entre as logos.

2022-08-16 16:12 UTC, wasp-lahis approved these changes

2022-08-16 16:13 UTC, merged