Insere página sobre programa de auxílio financeiro
pythonbrasil/pybr2022-site pull request #85
Opened 2022-08-21 15:59 UTC by cecivieira

# Modificado:

- Inserida página do programa de auxílio financeiro.
    - Criado componente `src/components/pages/FinancialAid`
    - Inserida referência do novo componente em `src/pages/index.js` e `src/components/shared/Header/index.js`

2022-08-21 16:00 UTC, cecivieira commented
Erro a ser corrigido:

![image](https://user-images.githubusercontent.com/30605862/185799925-ffd1ec04-2757-4c70-85d4-48cc297b0db9.png)

2022-08-21 19:28 UTC, rougeth requested changes

2022-08-21 19:28 UTC, rougeth commented on src/components/pages/FinancialAid/index.js
> +const DutyPage = ({ text }) => {
```suggestion
const FinancialAid = ({ text }) => {
```

2022-08-21 21:39 UTC, julianyraiol requested changes

2022-08-21 21:39 UTC, julianyraiol commented on src/configs/languages/text-ptbr.js
> +          type: "title",
Oi @cecivieira, não tem um tipo pro **title** mapeado antes, acredito que pode não funcionar. Testei no ambiente local e mudei esse [arquivo](https://github.com/pythonbrasil/pybr2022-site/blob/main/src/components/shared/DutyContent/index.js#L11)


comentei da linha 8 até a 19 e coloquei essa mudança aqui.

```
          var type_content =  text.type
          var content = ""
          if (type_content === "paragraph") {
            content= (<p key={contentKey}>{text.content}</p>)
          } 
          else if (type_content === "title") {
            content= (<h3 key={contentKey}>{text.content}</h3>)
          }
          else {
            content =
            (<ul key={`list-${contentKey}`}>
                {text.content.map((item) => (
                  <li key={`item-${item}`}>{item} </li>
                ))}
              </ul>)
          }
```

![image](https://user-images.githubusercontent.com/9119004/185811591-6b9674ea-26ab-4c7b-8f9d-015584ca1ef2.png)

2022-08-21 21:39 UTC, julianyraiol commented on src/components/pages/FinancialAid/style.scss
> +#duty {
É preciso adicionar o estilo para o botão, senão não vai ficar destacado. Por favor, adicionar esse trecho no css. 

 ```
button {
    margin-top: 36px;
    padding: 10px 23px;
    background: #e88c27;
    color: #fff;
    border-radius: 3px;
    font-size: calc(14 / 16 * 1rem);
    border: none;
    box-shadow: 0 0 3px 1px #00000030;
    font-weight: 700;
    text-transform: uppercase;
  }
```

fica assim 

![image](https://user-images.githubusercontent.com/9119004/185811942-8e069622-dc6e-4b60-99f5-29465f26bb29.png)

2022-08-21 21:52 UTC, wasp-lahis requested changes
No meu pc, ficou assim:

![Captura de tela 2022-08-21 175028](https://user-images.githubusercontent.com/7443249/185812377-797eda34-74e6-4c24-ac71-c9cf8350f6cb.png)

Acho que após as modificações que Ju comentou, vai dar bom o/

2022-08-21 21:57 UTC, julianyraiol reviewed
Quando a página renderiza, o livro fica por cima do título, tipo assim.
![image](https://user-images.githubusercontent.com/9119004/185812333-26200416-e886-4d45-a196-525e2a00a321.png)

A solução que eu achei foi mudar o css do componente [IconTitle](https://github.com/pythonbrasil/pybr2022-site/blob/main/src/components/shared/IconTitle/style.scss#L6). Adicionei o **width: 301px;** no **h2**.

```
h2 {
    width: 301px;
    font-family: "Montserrat", sans-serif;
    font-weight: 900;
    font-size: var(--h2-size-desktop);
    text-transform: uppercase;
  }
```

![image](https://user-images.githubusercontent.com/9119004/185812458-7beb8893-0d1b-45f9-9544-3608e0a99fd8.png)

2022-08-21 22:58 UTC, Delismachado commented on src/configs/languages/text-ptbr.js
> +          type: "title",
Fiz o mesmo teste  e acho que precisaria criar a condição para title e colocar um header e funciona certinho, pelo menos local foi. Além disso, achei mais um problema no index.js, esta dando erro no onClick, alterei a linha 38:
`<button type="button" onClick="window.open('https://forms.gle/qPkPYFHCRPG1JnpFA')">`
por:
`<button type="button" onClick={window.open('https://forms.gle/qPkPYFHCRPG1JnpFA')}>`
e deu bom!

2022-08-22 02:01 UTC, cecivieira commented on src/configs/languages/text-ptbr.js
> +          type: "title",
Fiz as alterações @julianyraiol @Delismachado. Obrigada!!!!
Acho que agora funcionou.

2022-08-22 02:02 UTC, cecivieira commented
@julianyraiol @wasp-lahis retirei o ícone do livro.
Obrigada pela revisão!!!

2022-08-22 02:11 UTC, cecivieira commented
@Delismachado agora os problemas que encontrei foi o título como na imagem e o click do botão não tá rolando (dá o erro da imagem abaixo):
![image](https://user-images.githubusercontent.com/30605862/185825071-f5cc9013-0016-4173-803f-5be9e4638114.png)
![image](https://user-images.githubusercontent.com/30605862/185825244-4b022378-14b9-4a39-b9c3-9c96ad02a358.png)

2022-08-22 14:01 UTC, julianyraiol commented
> 

oi @cecivieira, adiciona essas modificações, por favor.

```
const redirectToLink = () =>
  window.location.replace("https://forms.gle/qPkPYFHCRPG1JnpFA%22);
```

`<button type="button" onClick={redirectToLink}>
`

![image](https://user-images.githubusercontent.com/9119004/185939676-915a6076-1d48-4234-a256-db1d4e3bac9c.png)

2022-08-22 14:49 UTC, julianyraiol approved these changes
obrigada!!

2022-08-22 14:59 UTC, julianyraiol commented on src/components/pages/FinancialAid/index.js
> +              <IconTitle title={text.FINANCIALAID.LANDING.TITLE} icon={BookIcon}/>
iconTitle

2022-08-22 15:16 UTC, merged